### ISSUE TITLE
Build Failed status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#119]
```
greenhouse-effect : build
Build failed with status code 1:
Running "report-media" task
>> not-annotated: greenhouse-effect/mipmaps/infraredSource.png
>> missing-file: greenhouse-effect/mipmaps/infrared-source.png
>> missing-file: greenhouse-effect/mipmaps/microwave-source.png
>> missing-file: greenhouse-effect/mipmaps/uv-source.png
>> not-annotated: greenhouse-effect/mipmaps/microwaveSource.png
>> not-annotated: greenhouse-effect/mipmaps/uvSource.png
Fatal error: There is an issue with the licenses for media types.
Snapshot from 12/18/2021, 8:36:40 PM
```

**Comment by KatieWoe** [comment]
```
greenhouse-effect : build
Build failed with status code 1:
Running "report-media" task
>> not-annotated: greenhouse-effect/mipmaps/infraredSource.png
>> missing-file: greenhouse-effect/mipmaps/infrared-source.png
>> missing-file: greenhouse-effect/mipmaps/microwave-source.png
>> missing-file: greenhouse-effect/mipmaps/uv-source.png
>> not-annotated: greenhouse-effect/mipmaps/microwaveSource.png
>> not-annotated: greenhouse-effect/mipmaps/uvSource.png
Fatal error: There is an issue with the licenses for media types.
Snapshot from 12/20/2021, 1:01:53 PM

----------------------------------

greenhouse-effect : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1640030513564%22%2C%22timestamp%22%3A1640034269225%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: options contain keys that could be dangerous for mutate
Error: Assertion failed: options contain keys that could be dangerous for mutate
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at UpDownArrowPlot.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:75:17)
at UpDownArrowPlot.setDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:47:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:144:15
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Multilink.js:60:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Property.js:471:12)
at new EnergyBalancePlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:143:14)
at new EnergyBalancePanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:66:25)
at new LandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/LandscapeObservationWindow.js:141:32)
at new WaveLandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/waves/view/WaveLandscapeObservationWindow.js:14:5)
id: Bayes Chrome
Snapshot from 12/20/2021, 1:01:53 PM

----------------------------------

greenhouse-effect : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1640030513564%22%2C%22timestamp%22%3A1640033567808%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: options contain keys that could be dangerous for mutate
Error: Assertion failed: options contain keys that could be dangerous for mutate
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at UpDownArrowPlot.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:75:17)
at UpDownArrowPlot.setDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:47:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:144:15
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Multilink.js:60:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Property.js:471:12)
at new EnergyBalancePlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:143:14)
at new EnergyBalancePanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:66:25)
at new LandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/LandscapeObservationWindow.js:141:32)
at new WaveLandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/waves/view/WaveLandscapeObservationWindow.js:14:5)
id: Bayes Chrome
Snapshot from 12/20/2021, 1:01:53 PM

----------------------------------

greenhouse-effect : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1640030513564%22%2C%22timestamp%22%3A1640036260932%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: options contain keys that could be dangerous for mutate
Error: Assertion failed: options contain keys that could be dangerous for mutate
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at UpDownArrowPlot.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:75:17)
at UpDownArrowPlot.setDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:47:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:144:15
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Multilink.js:60:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Property.js:471:12)
at new EnergyBalancePlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:143:14)
at new EnergyBalancePanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:66:25)
at new LandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/LandscapeObservationWindow.js:141:32)
at new WaveLandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/waves/view/WaveLandscapeObservationWindow.js:14:5)
id: Bayes Chrome
Snapshot from 12/20/2021, 1:01:53 PM

----------------------------------

greenhouse-effect : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/phet-io-wrappers/phet-io-wrappers-tests.html?sim=greenhouse-effect&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: greenhouse-effect: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: options contain keys that could be dangerous for mutate
Error: Assertion failed: options contain keys that could be dangerous for mutate
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at UpDownArrowPlot.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:75:17)
at UpDownArrowPlot.setDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:47:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:144:15
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Multilink.js:60:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Property.js:471:12)
at new EnergyBalancePlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:143:14)
at new EnergyBalancePanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:66:25)
at new LandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/LandscapeObservationWindow.js:141:32)
at new WaveLandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/waves/view/WaveLandscapeObservationWindow.js:14:5)

Uncaught Error: Uncaught Error: Assertion failed: options contain keys that could be dangerous for mutateError: Assertion failed: options contain keys that could be dangerous for mutate
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/assert/js/assert.js:25:13)
at UpDownArrowPlot.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:75:17)
at UpDownArrowPlot.setDataSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/bamboo/js/UpDownArrowPlot.js:47:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:144:15
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Multilink.js:60:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/axon/js/Property.js:471:12)
at new EnergyBalancePlot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:143:14)
at new EnergyBalancePanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/EnergyBalancePanel.js:66:25)
at new LandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/common/view/LandscapeObservationWindow.js:141:32)
at new WaveLandscapeObservationWindow (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1640030513564/chipper/dist/js/greenhouse-effect/js/waves/view/WaveLandscapeObservationWindow.js:14:5)
id: Bayes Chrome
Snapshot from 12/20/2021, 1:01:53 PM
```

**Comment by jessegreenberg** [comment]
Error with the report-media task has been fixed. Ill look into the options keys issue next.

**Comment by jessegreenberg** [comment]
Fixed with https://github.com/phetsims/bamboo/commit/70148cada3ea44551c4203564d278aba31f58d65
