### ISSUE TITLE
CT Build failed with status code 1:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#162]
```
greenhouse-effect : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 26290ms
Building runnable repository (greenhouse-effect, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 7730ms
>> Unused sounds module: greenhouse-effect/sounds/irAbsorbanceHigh_mp3.js
>> Unused sounds module: greenhouse-effect/sounds/irAbsorbanceLow_mp3.js
>> Unused string: key=fluxMeter.sunlight, value=Sunlight
>> Unused string: key=fluxMeter.infrared, value=Infrared
>> Unused string: key=a11y.infraredRadiationRedirectingWithTemperaturePattern, value={{moreOrLess}} infrared radiation redirecting back to surface, now {{quantitativeTemperature}}.
>> Unused string: key=a11y.infraredRadiationEmittedFromSurfaceWithTemperaturePattern, value={{moreOrLess}} infrared radiation emitting from surface, now {{quantitativeTemperature}}.
>> Unused string: key=a11y.warmingStatement, value=Warming.
>> Unused string: key=a11y.coolingStatement, value=Cooling.
>> Unused string: key=a11y.concentrationPanel.concentration.label, value=Concentration
>> Production minification complete: 39580ms (6280730 bytes)
>> Debug minification complete: 1ms (32211374 bytes)
Building brand: phet-io
>> Webpack build complete: 7258ms
>> Unused sounds module: greenhouse-effect/sounds/irAbsorbanceHigh_mp3.js
>> Unused sounds module: greenhouse-effect/sounds/irAbsorbanceLow_mp3.js
>> Unused string: key=fluxMeter.sunlight, value=Sunlight
>> Unused string: key=fluxMeter.infrared, value=Infrared
>> Unused string: key=a11y.infraredRadiationRedirectingWithTemperaturePattern, value={{moreOrLess}} infrared radiation redirecting back to surface, now {{quantitativeTemperature}}.
>> Unused string: key=a11y.infraredRadiationEmittedFromSurfaceWithTemperaturePattern, value={{moreOrLess}} infrared radiation emitting from surface, now {{quantitativeTemperature}}.
>> Unused string: key=a11y.warmingStatement, value=Warming.
>> Unused string: key=a11y.coolingStatement, value=Cooling.
>> Unused string: key=a11y.concentrationPanel.concentration.label, value=Concentration
>> Production minification complete: 40635ms (6322706 bytes)
>> Debug minification complete: 42152ms (6646470 bytes)
>> no client guide found at ../phet-io-sim-specific/repos/greenhouse-effect/client-guide/examples.md, no guide being built.
>> no client guide found at ../phet-io-sim-specific/repos/greenhouse-effect/client-guide/migration-guide.md, no guide being built.
>> TypeScript compilation complete: 6821ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1653490621067/chipper/js/grunt/copySupplementalPhetioFiles.js:333:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1653490621067/chipper/js/grunt/buildRunnable.js:356:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1653490621067/chipper/js/grunt/Gruntfile.js:283:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1653490621067/chipper/js/grunt/Gruntfile.js:56:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Error in fulfilling chunk Promise: [Error: TypeError: Cannot read properties of undefined (reading 'padRatio')
at ma.reposition (http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:754818)
at http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:768766
at Array.forEach (<anonymous>)
at http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:768752
at Array.forEach (<anonymous>)
at Ma.layout (http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:768733)
at Ma.updateLayout (http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:752345)
at new ya (http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:772013)
at new ja (http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:806255)
at new Vg (http://localhost:45562/greenhouse-effect/build/phet-io/greenhouse-effect_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:887:1412482)]
Snapshot from 5/25/2022, 8:57:01 AM

----------------------------------

greenhouse-effect : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653490621067%22%2C%22timestamp%22%3A1653492226735%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: align left not supported, with the orientation HORIZONTAL, the valid values are top,bottom,center,origin,
Error: Assertion failed: align left not supported, with the orientation HORIZONTAL, the valid values are top,bottom,center,origin,
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/assert/js/assert.js:28:13)
at assert (FlowConfigurable.ts:178:16)
at (FlowBox.ts:207:4)
at (Node.ts:6280:10)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6263:6)
at mutate (Sizable.ts:178:19)
at mutate (FlowBox.ts:88:9)
at (HBox.ts:18:4)
id: Bayes Chrome
Snapshot from 5/25/2022, 8:57:01 AM

----------------------------------

greenhouse-effect : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653490621067%22%2C%22timestamp%22%3A1653492082140%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: align left not supported, with the orientation HORIZONTAL, the valid values are top,bottom,center,origin,
Error: Assertion failed: align left not supported, with the orientation HORIZONTAL, the valid values are top,bottom,center,origin,
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/assert/js/assert.js:28:13)
at assert (FlowConfigurable.ts:178:16)
at (FlowBox.ts:207:4)
at (Node.ts:6280:10)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6263:6)
at mutate (Sizable.ts:178:19)
at mutate (FlowBox.ts:88:9)
at (HBox.ts:18:4)
id: Bayes Chrome
Snapshot from 5/25/2022, 8:57:01 AM

----------------------------------

greenhouse-effect : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653490621067%22%2C%22timestamp%22%3A1653492887559%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
greenhouseEffect.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.title: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at listener (TinyEmitter.ts:93:8)
at emit (Sim.ts:964:24)
id: Bayes Chrome
Snapshot from 5/25/2022, 8:57:01 AM
```

**Comment by jbphet** [comment]
There are at least two errors occurring here, and the phet-io API one has been separately resolved.  The other, which was occurring due to fuzz tests, was because an alignment values used in an `HBox` is no longer supported due to work that was done for https://github.com/phetsims/sun/issues/48.  I removed the option, and the dialog seems to look fine.  I'll keep an eye on CT, and if the next round looks clear, I'll close this.

**Comment by jbphet** [comment]
CT had changed to green, see the screenshot below.  I think we're good here.  Closing.

![image](https://user-images.githubusercontent.com/3082831/170790922-ad566d64-9ae4-4627-834a-f7e4f25fe81c.png)
