### ISSUE TITLE
CT one of the items in the legend is too large

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#18]
```
greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1617155925767%22%2C%22timestamp%22%3A1617160888670%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/EnergyLegend.js:103:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:62:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/view/WavesScreenView.js:23:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/WavesScreen.js:32:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:929:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:937:25
id: Bayes Chrome
Snapshot from 3/30/2021, 7:58:45 PM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1617155925767%22%2C%22timestamp%22%3A1617167822571%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/EnergyLegend.js:103:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:62:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/view/WavesScreenView.js:23:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/WavesScreen.js:32:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:929:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:937:25
id: Bayes Chrome
Snapshot from 3/30/2021, 7:58:45 PM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1617155925767%22%2C%22timestamp%22%3A1617183306817%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/EnergyLegend.js:103:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:62:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/view/WavesScreenView.js:23:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/WavesScreen.js:32:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:929:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:937:25
id: Bayes Chrome
Snapshot from 3/30/2021, 7:58:45 PM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1617155925767%22%2C%22timestamp%22%3A1617199383871%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/EnergyLegend.js:103:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:62:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/view/WavesScreenView.js:23:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/greenhouse-effect/js/waves/WavesScreen.js:32:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:929:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/joist/js/Sim.js:937:25
id: Bayes Chrome
Snapshot from 3/30/2021, 7:58:45 PM
```

**Comment by jbphet** [comment]
This assertion looks like an explicit test that is being done in the new `EnergyLegend` type.  Since this was recently added by @jessegreenberg, I'm going to turn this over to him.

**Comment by jbphet** [comment]
I decided to take a look at this and it's a good thing I did - the problem was in the `ObservationWindow` class.  It was ending up very wide to to an unlimited button text width, so I've fixed this.  The `stringTest=xss` test is passing on my local copy now, so I think we're good to go.  Closing.
