### ISSUE TITLE
CT repo bamboo missing from package.json's phetLibs

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#27]
```
greenhouse-effect : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (greenhouse-effect, brands: phet)
Building brand: phet
>> Webpack build complete: 5226ms
>> Unused sounds module: greenhouse-effect/sounds/start-sunlight-arpeggio_mp3.js
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: repo bamboo missing from package.json's phetLibs for bamboo/js/BarPlot.js
at /data/share/phet/continuous-testing/ct-snapshots/1620278976259/chipper/js/grunt/buildRunnable.js:130:5
at Array.forEach (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1620278976259/chipper/js/grunt/buildRunnable.js:128:29)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at /data/share/phet/continuous-testing/ct-snapshots/1620278976259/chipper/js/grunt/Gruntfile.js:255:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1620278976259/chipper/js/grunt/Gruntfile.js:74:7)

Full Error details:
AssertionError [ERR_ASSERTION]: repo bamboo missing from package.json's phetLibs for bamboo/js/BarPlot.js
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620280394016%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/common/view/EnergyLegend.js:118:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:54:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/waves/view/WavesScreenView.js:27:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/waves/WavesScreen.js:33:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Sim.js:920:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Sim.js:928:25
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620290950404%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/common/view/EnergyLegend.js:118:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:54:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/waves/view/WavesScreenView.js:27:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/waves/WavesScreen.js:33:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Sim.js:920:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Sim.js:928:25
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1620278976259%22%2C%22timestamp%22%3A1620304952843%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/common/view/EnergyLegend.js:118:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:54:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/waves/view/WavesScreenView.js:27:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/greenhouse-effect/js/waves/WavesScreen.js:33:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Sim.js:920:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620278976259/joist/js/Sim.js:928:25
id: Bayes Chrome
Snapshot from 5/5/2021, 11:29:36 PM
```

**Comment by jbphet** [comment]
@jessegreenberg fixed this in 2b60b82c653bf73705c04b7e4f04589b22470deb, closing.
