### ISSUE TITLE
CT: Uncaught TypeError: Cannot read properties of undefined (reading 'phetioID')

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#343]
CT is currently failing periodically with the following error:

```
greenhouse-effect : phet-io-state-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1691370509159/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1691370509159%22%2C%22timestamp%22%3A1691398000811%7D
Uncaught TypeError: Cannot read properties of undefined (reading 'phetioID')
TypeError: Cannot read properties of undefined (reading 'phetioID')
at phetioID (ReferenceIO.ts:47:40)
at toStateObject (IOType.ts:269:32)
at toStateObject (MapIO.ts:54:32)
at toStateObject (IOType.ts:269:32)
at toStateObject (StateSchema.ts:157:67)
at defaultToStateObject (IOType.ts:362:57)
at defaultToStateObject (IOType.ts:266:29)
at toStateObject (PhetioStateEngine.ts:127:48)
at getValueJSON (PhetioStateEngine.ts:187:33)
at Array.forEach
id: Sparky Puppeteer
Snapshot from 8/6/2023, 7:08:29 PM
```

**Comment by jbphet** [comment]
I can duplicate this locally by running fuzz testing in the state wrapper, but it takes a while.

After some digging, I think I know what is going on, at least roughly.  The problem is occurring in the "source" (i.e. top) iframe of the state wrapper when the phetio state engine tries to serialize `PhotonAbsorbingEmittingLayer`, specifically its `photonToAbsorbedTimeMap` field, if there is a photon in this map.  This map tracks the amount of time that a given photon has been absorbed into the layer so that it can decide when to release it.  The problem appears to be that the photons are not themselves instances of `PhetioObject`, and don't have tandems, and the code that tries to serialize the `Map` instance seems to be assuming that they are.

We didn't see this problem earlier because prior to the work done for https://github.com/phetsims/greenhouse-effect/issues/167 the absorption time for photons was set to zero, so there were never any photons in this map when serialization was performed.

Photons were implemented as non-phetio objects in an attempt to maximize performance and minimize memory footprint, since there can be a lot of them in the model.  I'm now concerned that we can't deserialize references to things that aren't phet-io objects, which may make this approach unviable.  I'll reach out to the phet-io team for guidance on this.

**Comment by jbphet** [comment]
To duplicate this problem more quickly (versus just running fuzz in the state wrapper), follow these steps:

1. Change the default value of the `photonAbsorptionTime` option in `PhotonAbsorbingEmittingLayer` to 5 (seconds)
2. Launch the state wrapper with `screens=2` and _without_ the `fuzz` parameter
3. Press the "Start Sunlight" button
4. Hang out a few seconds.  The error is generally hit as soon as the IR photons radiate up from the Earth into the atmosphere a little ways

**Comment by jbphet** [comment]
I reached out on the phet-io Slack channel for some support, and @samreid said he can take a look at it tomorrow.  I'll assign this to him, and he can ping me back once he's had some time to look it over.

**Comment by jbphet** [comment]
@samreid - Here is a thought about how to get around this without having to make photons into PhetioObject instances: Instead of extracting and adding back specific photon instances, I could modify `PhotonAbsorbingEmittingLayer` to have a list of times and locations at which to create photons and then simply delete the absorbed ones from the photon collection and add new ones when the time expires.  That way we're not tracking any references to specific photons, so we don't have to working about serialization references.

Just a thought.  I'll be interested in what you think of the problem in general and this potential solution.

I'm also thinking that we might want better error messages in the phet-io code around this particular case.

**Comment by samreid** [comment]
I see that PhotonIO is data-type serialization (I also saw the usage in the observableArray), so would it work to change

```ts
photonToAbsorbedTimeMap: MapIO( ReferenceIO( Photon.PhotonIO ), NumberIO )
```

to

```ts
photonToAbsorbedTimeMap: MapIO( Photon.PhotonIO, NumberIO )
```
?

**Comment by jbphet** [comment]
Good thought.  Yes, I think that would work, because the `PhotonAbsorbingEmittingLayer` would be the only object instance with a reference to each of the photons in the `photonToAbsorbedTimeMap `, since they are removed from the photon collection when absorbed by the layer.  Therefore, the layer doesn't need to have a reference to an existing photon - the photons can just be re-created each time state is set.

I've tried it, and it appears to work.  I'll commit the change and see if the CT error disappears.  Thanks @samreid!

**Comment by jbphet** [comment]
This is no longer occurring on CT after the fix above was committed.  Closing.
