### ISSUE TITLE
CT Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#347]
```
greenhouse-effect : phet-io-api-compatibility : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028471691%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

greenhouseEffect.photonsScreen.view.observationWindow.cloudSeedProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":null,"validValues":null,"value":0.1979722345659211}
actual:
{"value":0.29582116129405295,"validValues":null,"units":null,"numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:371:22)
[URL] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692028136674%2Fgreenhouse-effect%2Fgreenhouse-effect_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028471691%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1692028136674%2Fgreenhouse-effect%2Fgreenhouse-effect_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028471691%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028471691%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

greenhouseEffect.photonsScreen.view.observationWindow.cloudSeedProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":null,"validValues":null,"value":0.1979722345659211}
actual:
{"value":0.29582116129405295,"validValues":null,"units":null,"numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

[PAGE ERROR] Error: Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

greenhouseEffect.photonsScreen.view.observationWindow.cloudSeedProperty._data.initialState differs.
Expected:
{"numberType":"FloatingPoint","range":{"max":"POSITIVE_INFINITY","min":"NEGATIVE_INFINITY"},"rangePhetioID":null,"units":null,"validValues":null,"value":0.1979722345659211}
actual:
{"value":0.29582116129405295,"validValues":null,"units":null,"numberType":"FloatingPoint","range":{"min":"NEGATIVE_INFINITY","max":"POSITIVE_INFINITY"},"rangePhetioID":null}

at window.assertions.assertFunction (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/assert/js/assert.js:28:13)
at XMLHttpRequest.<anonymous> (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/phet-io/js/phetioEngine.js:303:23)
[CONSOLE] continuous-test-load
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 8/14/2023, 9:48:56 AM

----------------------------------

greenhouse-effect : phet-io-state-fuzz : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028657646%7D
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
TypeError: Cannot read properties of undefined (reading 'x')
at (Vector2.ts:703:19)
at fromStateObject (Photon.ts:141:34)
at fromStateObject (createObservableArray.ts:445:123)
at Array.map
at map (createObservableArray.ts:445:39)
at applyState (createObservableArray.ts:486:171)
at applyState (IOType.ts:307:16)
at applyState (PhetioStateEngine.ts:422:9)
at setStateForPhetioObject (PhetioStateEngine.ts:325:13)
at Array.forEach
[URL] http://128.138.93.172//continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1692028136674%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgreenhouse-effect%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028657646%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1692028136674%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgreenhouse-effect%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028657646%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028657646%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028657646%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692028136674%22%2C%22timestamp%22%3A1692028657646%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/dot/js/Vector2.js:686:27)
at IOType.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/greenhouse-effect/js/common/model/Photon.js:112:33)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/axon/js/createObservableArray.js:376:87
at Array.map (<anonymous>)
at Proxy.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/axon/js/createObservableArray.js:376:40)
at Object.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/axon/js/createObservableArray.js:415:103)
at IOType.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/tandem/js/types/IOType.js:154:17)
at PhetioStateEngine.setStateForPhetioObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/phet-io/js/PhetioStateEngine.js:371:10)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/phet-io/js/PhetioStateEngine.js:285:14
at Array.forEach (<anonymous>)
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/dot/js/Vector2.js:686:27)
at IOType.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/greenhouse-effect/js/common/model/Photon.js:112:33)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/axon/js/createObservableArray.js:376:87
at Array.map (<anonymous>)
at Proxy.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/axon/js/createObservableArray.js:376:40)
at Object.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/axon/js/createObservableArray.js:415:103)
at IOType.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/tandem/js/types/IOType.js:154:17)
at PhetioStateEngine.setStateForPhetioObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/phet-io/js/PhetioStateEngine.js:371:10)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692028136674/chipper/dist/js/phet-io/js/PhetioStateEngine.js:285:14
at Array.forEach (<anonymous>)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 8/14/2023, 9:48:56 AM
```

**Comment by jbphet** [comment]
I think I've fixed this, see https://github.com/phetsims/scenery-phet/issues/813#issuecomment-1679743512.  I'll see if CT looks clear in the morn and will close this if so.

**Comment by jbphet** [comment]
This error is no longer appearing in CT, closing.
