### ISSUE TITLE
CT: Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#35]
I've done a bit of investigation on this, and it is is actually a problem caused by the observation window leaving insufficient space for the energy legend.

@jessegreenberg - Two things:
- The root of the problem is that several of the items that were recently added to the observation window, such as the thermometer and the energy balance panel, don't have anything preventing them from getting huge during some of the string tests.  Can you add some maxWidth values to resolve this?
- The wording of the assertion is a bit misleading and it took me a little while to figure out what was going on.  Can you add one to make sure the the width value provided to the `EnergyLegend` is reasonable in case we run into this again (which seems quite possible)?

**Comment by KatieWoe** [comment]
```
greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1621238751604%22%2C%22timestamp%22%3A1621243027540%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/common/view/EnergyLegend.js:118:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:54:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/waves/view/WavesScreenView.js:27:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/waves/WavesScreen.js:33:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/joist/js/Sim.js:927:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/joist/js/Sim.js:935:25
id: Bayes Chrome
Snapshot from 5/17/2021, 2:05:51 AM

----------------------------------

greenhouse-effect : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/greenhouse-effect_en.html?continuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1621238751604%22%2C%22timestamp%22%3A1621248303611%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: one of the items in the legend is too large, extends beyond width
Error: Assertion failed: one of the items in the legend is too large, extends beyond width
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/assert/js/assert.js:25:13)
at new EnergyLegend (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/common/view/EnergyLegend.js:118:15)
at new GreenhouseEffectScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/common/view/GreenhouseEffectScreenView.js:54:25)
at new WavesScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/waves/view/WavesScreenView.js:27:5)
at WavesScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/greenhouse-effect/js/waves/WavesScreen.js:33:16)
at WavesScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/joist/js/Screen.js:253:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/joist/js/Sim.js:927:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621238751604/joist/js/Sim.js:935:25
id: Bayes Chrome
Snapshot from 5/17/2021, 2:05:51 AM
```

**Comment by jessegreenberg** [comment]
Thanks for investigating. I went through and made the screen friendly for i18n in general. I can see how that commit message is confusing. It now reads like:
>'provided width of is not large enough to fit contents, provide larger width or make contents smaller'

which should hopefully clarify the intention of the assertion.

I think this can be closed now.
