### ISSUE TITLE
CT: Uncaught TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by jbphet** [phetsims/greenhouse-effect#353]
There is a phet-io state fuzz error in CT, details below

<details>

```
greenhouse-effect : phet-io-state-fuzz : unbuilt
http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692204540892%22%2C%22timestamp%22%3A1692204961748%7D
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
TypeError: Cannot read properties of undefined (reading 'x')
at (Vector2.ts:703:19)
at fromStateObject (Photon.ts:141:34)
at fromStateObject (createObservableArray.ts:445:123)
at Array.map
at map (createObservableArray.ts:445:39)
at applyState (createObservableArray.ts:486:171)
at applyState (IOType.ts:307:16)
at applyState (PhetioStateEngine.ts:422:9)
at setStateForPhetioObject (PhetioStateEngine.ts:325:13)
at Array.forEach
[URL] http://128.138.93.172//continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1692204540892%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgreenhouse-effect%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692204540892%22%2C%22timestamp%22%3A1692204961748%7D
[NAVIGATED] http://128.138.93.172//continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1692204540892%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dgreenhouse-effect%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692204540892%22%2C%22timestamp%22%3A1692204961748%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692204540892%22%2C%22timestamp%22%3A1692204961748%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692204540892%22%2C%22timestamp%22%3A1692204961748%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1692204540892%22%2C%22timestamp%22%3A1692204961748%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/dot/js/Vector2.js:686:27)
at IOType.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/greenhouse-effect/js/common/model/Photon.js:112:33)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/axon/js/createObservableArray.js:376:87
at Array.map (<anonymous>)
at Proxy.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/axon/js/createObservableArray.js:376:40)
at Object.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/axon/js/createObservableArray.js:415:103)
at IOType.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/tandem/js/types/IOType.js:154:17)
at PhetioStateEngine.setStateForPhetioObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/phet-io/js/PhetioStateEngine.js:371:10)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/phet-io/js/PhetioStateEngine.js:285:14
at Array.forEach (<anonymous>)
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/dot/js/Vector2.js:686:27)
at IOType.fromStateObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/greenhouse-effect/js/common/model/Photon.js:112:33)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/axon/js/createObservableArray.js:376:87
at Array.map (<anonymous>)
at Proxy.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/axon/js/createObservableArray.js:376:40)
at Object.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/axon/js/createObservableArray.js:415:103)
at IOType.applyState (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/tandem/js/types/IOType.js:154:17)
at PhetioStateEngine.setStateForPhetioObject (http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/phet-io/js/PhetioStateEngine.js:371:10)
at http://128.138.93.172//continuous-testing/ct-snapshots/1692204540892/chipper/dist/js/phet-io/js/PhetioStateEngine.js:285:14
at Array.forEach (<anonymous>)
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 8/16/2023, 10:49:00 AM
```

</details>

**Comment by jbphet** [comment]
This should now be fixed on the main branch.  I'll check CT tomorrow and close if clear.

**Comment by jbphet** [comment]
CT is clean, closing.
