### ISSUE TITLE
CT: MigrationReport problem: phetioIDNotInNewAPI

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/greenhouse-effect#376]
This error has been occurring on every CT cycle.   It also occurs if you run the Migration wrapper manually, so I did not add the automated-testing label. 

```
greenhouse-effect : migration : 1.2->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D
Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:164:22)
at reportForContext (MigrationEngine.ts:86:22)
at migrate (StandardPhetioWrapper.ts:279:37)
at (Client.ts:1490:19)
at async (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/migration.js:219:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dgreenhouse-effect%26oldVersion%3D1.2%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dgreenhouse-effect%26oldVersion%3D1.2%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/studio/?sim=greenhouse-effect&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D&phetioMigrationReport=assert&fuzz&locales=*
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/greenhouse-effect/1.2/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] https://phet-io.colorado.edu/sims/greenhouse-effect/1.2/greenhouse-effect_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702726045571%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] layer 1 atEquilibrium = true
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:141:23)
at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:65:23)
at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:196:38)
at async Client.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/Client.js:1324:20)
at async http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/migration.js:219:11
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 12/16/2023, 4:19:31 AM

----------------------------------

greenhouse-effect : migration : 1.2->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D
Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:164:22)
at reportForContext (MigrationEngine.ts:86:22)
at migrate (StandardPhetioWrapper.ts:279:37)
at (Client.ts:1490:19)
at async (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/migration.js:219:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dgreenhouse-effect%26oldVersion%3D1.2%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dgreenhouse-effect%26oldVersion%3D1.2%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/studio/?sim=greenhouse-effect&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D&phetioMigrationReport=assert&fuzz&locales=*
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/greenhouse-effect/1.2/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] https://phet-io.colorado.edu/sims/greenhouse-effect/1.2/greenhouse-effect_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702730861812%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] layer 1 atEquilibrium = true
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:141:23)
at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:65:23)
at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:196:38)
at async Client.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/Client.js:1324:20)
at async http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/migration.js:219:11
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 12/16/2023, 4:19:31 AM

----------------------------------

greenhouse-effect : migration : 1.2->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D
Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:164:22)
at reportForContext (MigrationEngine.ts:86:22)
at migrate (StandardPhetioWrapper.ts:279:37)
at (Client.ts:1490:19)
at async (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/migration.js:219:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dgreenhouse-effect%26oldVersion%3D1.2%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702725571789%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dgreenhouse-effect%26oldVersion%3D1.2%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/?sim=greenhouse-effect&oldVersion=1.2&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/studio/?sim=greenhouse-effect&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D&phetioMigrationReport=assert&fuzz&locales=*
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/greenhouse-effect/greenhouse-effect_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=greenhouse-effect&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D&phetioMigrationReport=assert&fuzz&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/greenhouse-effect/1.2/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] https://phet-io.colorado.edu/sims/greenhouse-effect/1.2/greenhouse-effect_all_phet-io_debug.html?ea&postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22migration%22%2C%221.2-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1702725571789%22%2C%22timestamp%22%3A1702737104578%7D&phetioMigrationReport=assert&fuzz&exposeStandardPhetioWrapper&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] layer 1 atEquilibrium = true
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer1.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer2.showTemperatureProperty",
"greenhouseEffect.layerModelScreen.view.observationWindow.atmosphereLayer3.showTemperatureProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/assert/js/assert.js:28:13)
at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:141:23)
at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:65:23)
at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:196:38)
at async Client.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/chipper/dist/js/phet-io-wrappers/common/js/Client.js:1324:20)
at async http://128.138.93.172/continuous-testing/ct-snapshots/1702725571789/phet-io-wrappers/migration/migration.js:219:11
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 12/16/2023, 4:19:31 AM
```

**Comment by pixelzoom** [comment]
Here's the Migration Report:

<img width="833" alt="screenshot_2935" src="https://github.com/phetsims/greenhouse-effect/assets/3046552/992606d8-fb04-4c39-9a03-e78e90a97fce">

**Comment by zepumph** [comment]
@jbphet was this renamed or moved or uninstrumented? Either way we have MigrationProcessors to handle it. Take a look at the doc and let me know if you run into any questions.

**Comment by jbphet** [comment]
This should now be fixed.  I'll verify that CT clears up before closing it.

**Comment by jbphet** [comment]
CT now looks clear.  Closing.
