### ISSUE TITLE
CT there should be at least as many PDOMDisplays as Displays

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#51]
```
greenhouse-effect : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1626224015422%22%2C%22timestamp%22%3A1626226139704%7D
Uncaught Error: Uncaught Error: Assertion failed: there should be at least as many PDOMDisplays as Displays
Error: Assertion failed: there should be at least as many PDOMDisplays as Displays
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/assert/js/assert.js:25:13)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:284:15)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:303:35)
at PDOMDisplaysInfo.removePDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:303:35)
at PDOMDisplaysInfo.removeAllPDOMDisplays (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:236:10)
at PDOMDisplaysInfo.onVisibilityChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/scenery/js/accessibility/pdom/PDOMDisplaysInfo.js:119:14)
at WavesScreenView.onVisiblePropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/scenery/js/nodes/Node.js:3752:28)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/axon/js/TinyEmitter.js:68:48)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/axon/js/TinyForwardingProperty.js:181:10)
at TinyForwardingProperty.onTargetPropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626224015422/axon/js/TinyForwardingProperty.js:128:10)
id: Bayes Chrome
Snapshot from 7/13/2021, 6:53:35 PM
```

**Comment by jessegreenberg** [comment]
This is the same as #46, it is just that the assertion message message was improved, closing this one and will update the title of that issue since there was some investigation there already.
