### ISSUE TITLE
CT perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#69]
```
greenhouse-effect : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (greenhouse-effect, brands: phet, phet-io)
Building brand: phet
Fatal error: Perennial task failed:
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../bamboo/js/LabelSet.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629999029596/greenhouse-effect/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:811:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:673:25
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:882:8
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
Full Error details:
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../bamboo/js/LabelSet.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629999029596/greenhouse-effect/js/common/view'

Webpack build errors: [
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../bamboo/js/LabelSet.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629999029596/greenhouse-effect/js/common/view'
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/Compilation.js:1773:28
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:811:13
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:286:22
at eval (eval at create (/data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:442:22
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:673:25
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:882:8
at /data/share/phet/continuous-testing/ct-snapshots/1629999029596/chipper/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
resolve '../../../../bamboo/js/LabelSet.js' in '/data/share/phet/continuous-testing/ct-snapshots/1629999029596/greenhouse-effect/js/common/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1629999029596/greenhouse-effect/package.json (relative path: ./js/common/view)
Field 'browser' doesn't contain a valid alias configuration
using description file: /data/share/phet/continuous-testing/ct-snapshots/1629999029596/bamboo/package.json (relative path: ./js/LabelSet.js)
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629999029596/bamboo/js/LabelSet.js doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629999029596/bamboo/js/LabelSet.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629999029596/bamboo/js/LabelSet.js.json doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1629999029596/bamboo/js/LabelSet.js.wasm doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/1629999029596/bamboo/js/LabelSet.js doesn't exist
]
Snapshot from 8/26/2021, 11:30:29 AM
```

**Comment by jbphet** [comment]
I've never seen this error, and I just looked at CT and this problem hasn't happened for the last 20 cycles, which is as far back as I looked.  I'm going to assume that this was something spurious and close it.
