### ISSUE TITLE
CT Impossible set state from iterate

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/greenhouse-effect#81]
```
greenhouse-effect : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io-wrappers/state/?sim=greenhouse-effect&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22greenhouse-effect%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631353521152%22%2C%22timestamp%22%3A1631580467192%7D
Uncaught Error: Uncaught Error: Assertion failed: Impossible set state from iterate; unset state:
{
"greenhouseEffect.wavesScreen.model.waveGroup.wave_0": {
"wavelength": 5.8e-7,
"origin": {
"x": -19550,
"y": 50000
},
"directionOfTravel": {
"x": 0,
"y": -1
},
"propagationLimit": 0,
"startPoint": {
"x": -19550,
"y": 50000
},
"length": 34464,
"isSourced": true,
"existenceTime": 4.308000000000002,
"phaseOffsetAtOrigin": 5.315574769873927,
"intensityAtStart": 0.5,
"modelObjectToAttenuatorMap": [
[
{
"phetioID": "greenhouseEffect.optionalTandem"
},
{
"attenuation": 0.3,
"distanceFromStart": 30000
}
]
],
"renderingWavelength": 8000
}
}
Error: Assertion failed: Impossible set state from iterate; unset state:
{
"greenhouseEffect.wavesScreen.model.waveGroup.wave_0": {
"wavelength": 5.8e-7,
"origin": {
"x": -19550,
"y": 50000
},
"directionOfTravel": {
"x": 0,
"y": -1
},
"propagationLimit": 0,
"startPoint": {
"x": -19550,
"y": 50000
},
"length": 34464,
"isSourced": true,
"existenceTime": 4.308000000000002,
"phaseOffsetAtOrigin": 5.315574769873927,
"intensityAtStart": 0.5,
"modelObjectToAttenuatorMap": [
[
{
"phetioID": "greenhouseEffect.optionalTandem"
},
{
"attenuation": 0.3,
"distanceFromStart": 30000
}
]
],
"renderingWavelength": 8000
}
}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/assert/js/assert.js:25:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/PhetioStateEngine.js:356:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/PhetioStateEngine.js:247:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/PhetioStateEngine.js:266:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/phetioEngine.js:1053:32)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/phetioCommandProcessor.js:304:51)
at getReturn (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/phetioCommandProcessor.js:179:36)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/phetioCommandProcessor.js:183:16
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/phet-io/js/phetioCommandProcessor.js:177:30)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:45:21 AM
```

**Comment by jbphet** [comment]
There is a good change that this was fixed by the changes made to address #79.  I'll keep an eye on CT and see if this problem recurs.

**Comment by jbphet** [comment]
Here's a screenshot from CT that indicate the last time this issue occurred:

![image](https://user-images.githubusercontent.com/3082831/133501706-7c1338d1-2eb3-487b-a2f8-31f25125f098.png)

**Comment by jbphet** [comment]
CT looks clear, closing.
